### ISSUE TITLE
Alpha argument to Color.random() should have a name

### ISSUE THREAD

**Issue by BurntCaramel** [nvzqz/RandomKit#1]
i.e.
```
UIColor.random(alpha: true)
```

**Comment by nvzqz** [comment]
Thanks, fixed in 8647eaa04d36730ff32fc9aa0cf8c92208721a65

**Comment by BurntCaramel** [comment]
Wow that was fast! Nice library BTW!

**Comment by nvzqz** [comment]
I'm glad you like it. Thanks!

**Comment by nvzqz** [comment]
This change is now featured in the [v1.2.0 release](https://github.com/nvzqz/RandomKit/releases/tag/v1.2.0).
