### ISSUE TITLE
EXC_BAD_INSTRUCTION on random Int between Int.min and Int.max

### ISSUE THREAD

**Issue by phimage** [nvzqz/RandomKit#11]
When developing a feature about Lattice (ordered with min and max bound) for RandomKit
https://github.com/phimage/RandomKit/blob/feature-lattice/RandomKit/RandomType.swift
after doing one for my maths project
https://github.com/phimage/Arithmosophi/commit/e4db5e260e5912674c457d6db103db28fa9f273f

an issue occurs. 

Doing random on min...max range of a Int (and other type) failed with EXC_BAD_INSTRUCTION

A test to add to check this error
```swift
    func testRandomIntMax() {
        let min = Int.min
        let max =  Int.max
        Int.random(min...max)
    }
```

**Comment by nvzqz** [comment]
The `EXC_BAD_INSTRUCTION` is due to the overflow when subtracting `Int.min` from `Int.max`. I'm not sure of a way around it.
