### ISSUE TITLE
Randomized names

### ISSUE THREAD

**Issue by oasisweng** [nvzqz/RandomKit#12]
Can you implement a randomized name feature for String object?

**Comment by nvzqz** [comment]
Sorry I haven't gotten around to this yet. I'll work on it when I finish with my exams this week. It's definitely a feature I want in here.

**Comment by AnthonyMDev** [comment]
+1

**Comment by nvzqz** [comment]
I've changed the direction of RandomKit to generate data only for types in the Swift standard library, Foundation, Cocoa, and CoreGraphics. Once 2.0.0 is released, I'll be making a fake data generation library that relies on RandomKit.
