### ISSUE TITLE
Remove "fake" from function names

### ISSUE THREAD

**Issue by markohlebar** [nvzqz/RandomKit#13]
Using `fake` in function name doesn't convey any additional information to the programmer, because it's already obvious from using `Random` that the result will indeed be randomly generated. 
`Random.phoneNumber()` would make for a nicer API in my opinion.

**Comment by nvzqz** [comment]
Thanks for the suggestion and I agree. Changed in 8e50665cbdcf82a0d8920f2dddf97892ececfd7f
