### ISSUE TITLE
New pod version for swift 3.0

### ISSUE THREAD

**Issue by ldiqual** [nvzqz/RandomKit#21]
@nvzqz Now that Xcode 8 GM is out and that RandomKit is compatible with the latest version of swift 3.0, how about releasing a new version of the library and publish it on cocoapods? That'd make dependency management a lot easier :)

**Comment by AnthonyMDev** [comment]
Yes please!

**Comment by ldiqual** [comment]
@nvzqz Can you please publish a new version so we can stop relying on the master branch itself? Thank you :)

**Comment by nvzqz** [comment]
I'm in the process of making fixes to RandomKit along with adding new features. A new version should be expected within the next week.
