### ISSUE TITLE
Build error, can't build version 1.5.0

### ISSUE THREAD

**Issue by MKGitHub** [nvzqz/RandomKit#3]
I downloaded the source code zip, and put the swift files in my project.

![2015-10-25 at 14 53 19](https://cloud.githubusercontent.com/assets/535550/10715947/3864421e-7b28-11e5-81b0-d43ed5d70b88.png)

**Comment by nvzqz** [comment]
I decided to put all of the imports from the C standard library into a module called "C", but it's lead to some issues, including not being able to push to Cocoapods.

Just import Foundation instead in your case.

**Comment by nvzqz** [comment]
Fixed 5580849314612f52697de148c2485789cd23bc64
