### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by mattgallagher** [nvzqz/RandomKit#34]
This repository uses the Xoroshiro, MersenneTwister and possibly other implementations taken from Cocoa with Love, first featured from here:

https://www.cocoawithlove.com/blog/2016/05/19/random-numbers.html

As they appear in this repository, all copyright and credit has been removed from this code.

You're required, as per the terms of the copyrights on the website and my github repository to keep the original copyright message. Please return the original copyright to these files and the top-level LICENSE file or remove the copied code which is currently used without license.

**Comment by nvzqz** [comment]
To be clear, the license found [here](https://www.cocoawithlove.com/about/) should be in the header for the code for `Xoroshiro`, `MersenneTwister`, and placed in the `LICENSE.md` file in conjunction with the project license, yes?

**Comment by mattgallagher** [comment]
Yes, that is what I'm asking.

**Comment by nvzqz** [comment]
Fixed with https://github.com/nvzqz/RandomKit/commit/9f157b8d67eee00d5ad423c698341145db1eeef9

Let me know if anything else should be done. I'm very sorry for not attributing you beforehand.

**Comment by mattgallagher** [comment]
Thank you.
