### ISSUE TITLE
Does not compile with Swift 4

### ISSUE THREAD

**Issue by ldiqual** [nvzqz/RandomKit#35]
I get 20 errors when compiling with Swift 4:

![image](https://user-images.githubusercontent.com/941453/27116123-40ba3508-5084-11e7-9f4f-25e58c8825cf.png)

**Comment by ldiqual** [comment]
My bad, didn't see https://github.com/nvzqz/RandomKit/issues/33

**Comment by nvzqz** [comment]
@ldiqual Released [v5.1.0](https://github.com/nvzqz/RandomKit/releases/tag/v5.1.0) which supports Swift 3.2 and 4
