### ISSUE TITLE
Xcode 9/iOS 11 generating errors

### ISSUE THREAD

**Issue by danipralea** [nvzqz/RandomKit#37]
Hi guys!
I have been compiling on of my projects in Xcode 9 (beta) and there's a few errors being generated by RandomKit. any chance you can have a look at that?

More specifically:
![screenshot 2017-07-05 09 45 02](https://user-images.githubusercontent.com/768893/27852156-ae8d9ba4-6166-11e7-9a11-99278f3ce7f9.png)

Thanks in advance!

**Comment by nvzqz** [comment]
Are you using release [v5.1.0](https://github.com/nvzqz/RandomKit/releases/tag/v5.1.0)?

**Comment by danipralea** [comment]
I don't know to be honest. I just have `pod 'RandomKit'` in my Podfile

**Comment by nvzqz** [comment]
Try doing:
```sh
pod repo update
```

Your local specs might by out of sync?

**Comment by danipralea** [comment]
that did it. I don't have errors in the framework itself, but I have errors where I'm using it.

**Comment by nvzqz** [comment]
Can you please post an image showing these errors?

**Comment by nvzqz** [comment]
@danipralea are you still experiencing these errors?

**Comment by danipralea** [comment]
@nvzqz I have not tried yet, cause we postponed the transition to Xcode 9 & iOS 11

**Comment by nvzqz** [comment]
@danipralea any update on your situation?

**Comment by danipralea** [comment]
the same for now 😢

**Comment by nvzqz** [comment]
I see what the problem is: RandomKit 5 and after uses 'in' instead of 'within' for an argument label.

I suggest doing a find & replace of 'within:' to 'in:' within your project.

**Comment by danipralea** [comment]
is there cross-compatibility between Swift 4 and Swift 3?

**Comment by nvzqz** [comment]
RandomKit 5 supports Swift 3.2 and Swift 4, yes.

**Comment by danipralea** [comment]
I'm still not sure what I need to do to work both on Xcode 8 and Xcode 9 😢

**Comment by nvzqz** [comment]
What errors are you getting?

**Comment by danipralea** [comment]
the ones above? 😛

**Comment by danipralea** [comment]
oh, just replace. saw it later. cool, I will try it later

**Comment by nvzqz** [comment]
@danipralea have you resolved this on your side?

**Comment by nvzqz** [comment]
@danipralea Closing this issue now. If you're still experiencing problems, feel free to reopen it.
