### ISSUE TITLE
Does not compile with swift 4.1

### ISSUE THREAD

**Issue by buscarini** [nvzqz/RandomKit#47]
/Users/josanchez/prog/SecretSanta/App/Code/Pods/RandomKit/Sources/RandomKit/Extensions/Swift/Collection+RandomKit.swift:84:17: Invalid redeclaration of 'uncheckedRandom(in:using:)'

/Users/josanchez/prog/SecretSanta/App/Code/Pods/RandomKit/Sources/RandomKit/Extensions/Swift/Collection+RandomKit.swift:90:73: Type 'Collection.IndexDistance' (aka 'Int') in conformance requirement does not refer to a generic parameter or associated type

**Comment by DK-Webentwicklung** [comment]
Same! Please fix this. Thx!

**Comment by tengyifei** [comment]
I made a PR #48
