### ISSUE TITLE
Playground not working 

### ISSUE THREAD

**Issue by vineethvijayan** [nvzqz/RandomKit#5]
I opened RandomKit.playground and it shows 

'No Such Module 'RandomKit''

I am using xcode 7 and swift 2

**Comment by nvzqz** [comment]
Did you build the OS X target?

I'll also get this sometimes but after a few seconds it'll find the framework.

**Comment by vineethvijayan** [comment]
I just opened RandomKit.playground file 
Is there any other way should open?

**Comment by nvzqz** [comment]
Open RandomKit.workspace and it should work.

**Comment by vineethvijayan** [comment]
Nope same effect sorry

**Comment by nvzqz** [comment]
Are you building the framework, though?

Open the workspace, select the OS X target on the top left, and hit cmd+b to build it. Then open the playground.

**Comment by vinbhai4u** [comment]
@nvzqz thanks mate, so if I create a playground it wont work standalone rite?

**Comment by nvzqz** [comment]
From my understanding, Xcode requires the opened playground to be in the same workspace as the framework.

So no, @vinbhai4u I don't think a standalone playground would work.

**Comment by vinbhai4u** [comment]
Playground works fine alone, if no extra libs added.
I wish I could test some pods easily if it was possible. Anyways thanks brother.
