### ISSUE TITLE
Consider supporting Xcode 10 / Swift 4.2

### ISSUE THREAD

**Issue by DanielAsher** [nvzqz/RandomKit#58]
Currently building in Xcode 10 / Swift 4.2 results in a number of errors such as:

```Type 'UnsafeBufferPointer<Element>' does not conform to protocol 'RandomRetrievableInRange'```

in Collection+RandomKit.swift

**Comment by janoonaj** [comment]
Hi @DanielAsher , as you faced this problem months ago, can you recommend any alternative to RandomKit for XCode 10?

**Comment by phimage** [comment]
Hi @janoonaj,

Could you explain me the feature you want to use with RandomKit
Because swift library contains now some of them.
